# *************************************************************************************************
# Site settings
# *************************************************************************************************
baseURL = "http://alternative.eladrom.com"
# baseURL = "http://localhost:3000"
copyright = "פורסם תחת רשיון 'למי אכפת?' © 2017"
DefaultContentLanguage = "en"
googleAnalytics = "UA-101896525-1"
languageCode = "he-il"
publishdir = "../../dist/dev/"
title = "אלעד רום | מטפל אלטרנטיבי"
languageName = "עברית"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    email = "eladrome@gmail.com"
    googleMaps = "AIzaSyDMiwqXrlELchoMbRtOXfaZ8u77BqFP_eo"

[[menu.main]]
    name = "בית"
    identifier = "home"
    weight = -120
    url = "/"
[[menu.main]]
    name = "בלוג"
    identifier = "blog"
    weight = -110
    url = "/post/"
[[menu.main]]
    name = "שאלות נפוצות"
    identifier = "faq"
    weight = -100
    url = "/faq/"
